### ISSUE TITLE
Feature request: Remove old CSS after injecting new CSS

### ISSUE THREAD

**Issue by EliezerB123** [simov/styler#1]
Hey! As I'm working with CSS, the inspector gets bigger, and bigger, and more unreadable the more changes I make, because every time I change the CSS, it adds a new block without removing the old block.

If you could remove the old CSS after injecting new CSS, that would be fantastic.

(To avoid too much unnecessary repaint, we should first inject the new CSS, THEN remove the old stuff.)

Add this code to the inject of the CSS:

    // Label our new element, so it can be removed later.
    style.setAttribute('class', 'Styler-CSS');  

    // Get every **.Styler-CSS** except the last one.
    var oldElements = document.getElementsByClassName('Styler-CSS');
    oldElements = oldElements.splice(oldElements.length - 1); 
    if (oldElements.length > 0) {
         // If there is at least one **oldElement**, remove them all.
         Array.from(oldElements).forEach(element => element.remove());
    }

**Comment by EliezerB123** [comment]
As a side note, I mostly want this feature on Styler-Classic, because that's the plugin I'm using.....

:open_mouth:

**Comment by simov** [comment]
I'm not sure how is this related to this extension? Are you sure this is the correct repo? This extension is not even published on Chrome Store.

**Comment by EliezerB123** [comment]
My mistake, and apologies. I thought this was the Github repro for this extension:

https://chrome.google.com/webstore/detail/styler/bogdgcfoocbajfkjjolkmcdcnnellpkb?hl=en

**Comment by simov** [comment]
No problem. I'm closing this then.
