### ISSUE TITLE
Upgrade to chrome extension manifest.json 3

### ISSUE THREAD

**Issue by un33k** [simov/styler#2]
Manifest V3 will prevent external script / style execution.
I wonder if this is considered OK for Styler.

If so, it would be great to see an updated version of the extension on Google Chrome.

**Comment by simov** [comment]
We have time until Jan 2023 https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/ but thanks for the reminder, I will have to take a look at it.

**Comment by un33k** [comment]
Thank you. Yeah, I am building a chat overlay, and it'd be nice to be able to rely on this post 2023.  Looking forward your V3.  Thx

**Comment by simov** [comment]
I have updated the extension to use manifest v3. It seems to be working without issues for the past couple of months, so you can pull it from the `main` branch. Also make sure you check out the README again as I did some changes to the configuration data structure. The manifest v2 version is still available in the `mv2` branch.

**Comment by un33k** [comment]
Excellent!.  Thx
